apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mmbxx425h-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mmbxx425h-java-quarkus-gitops